### PR TITLE
Add GPT-4 Turbo

### PR DESCRIPTION
**Pull request by akynau**
This PR will:
- add support for `gpt-4-turbo`
- add support for `gpt-4-turbo-2024-04-09`

See: https://platform.openai.com/docs/models/gpt-4-turbo-and-gpt-4

Should close https://github.com/dqbd/tiktoken/issues/96 on approval and merge.

### CODE REVIEW

**Comment by akynau** [comment]
Hey @dqbd, could I please ask for a review on this PR? Thanks!

**Comment by jgui1129** [comment]
Waiting. Following

**Comment by dqbd** [comment]
Thank you @akynau!

**Comment by akynau** [comment]
@dqbd No worries!

But there is a conflict with publishing the package with version 1.0.13. Do you need to commit a change set? Let me know if I can help. Thanks!

**Pull request merged**
