### PR TITLE
feat: Add missing models

### PR DESCRIPTION
**Pull request by kdwkr**
Add missing models and types for WASM.

### CODE REVIEW

**Comment by kdwkr** [comment]
@dqbd Could you review and merge this PR?

**Comment by kiejo** [comment]
It looks like a similar pull request (https://github.com/dqbd/tiktoken/pull/51) has already been merged, but it hasn't been released as a new version yet.

**Comment by kdwkr** [comment]
@kiejo The pull request has a few omissions. So I created this pull request for add some missed types and model.
And alreay the version that applied the pull request released. https://www.npmjs.com/package/tiktoken

**Comment by kiejo** [comment]
Oh that's good to know and could explain why I got an `Invalid model: gpt-3.5-turbo-0613` error when trying the newest version (`1.0.8`). It sounds like your pull request might fix that!

**Comment by dqbd** [comment]
lgtm! thanks for the fix

**Comment by dqbd** [comment]
Should be now released as 1.0.9

**Pull request merged**
