### PR TITLE
Add support for gpt-4-1106-preview

### PR DESCRIPTION
**Pull request by pkallos**
Adding support for GPT4-turbo

Could use a bit of guidance on how to test/validate, reached some hurdles with the build.

`wrangle` 1.xx is deprecated which is causing issues.

### CODE REVIEW

**Comment by pkallos** [comment]
@dqbd did my best here, not sure how to handle wrangler since I have never used but build/test passes now

**Comment by missuo** [comment]
@dqbd seems to have been inactive for some time, and my project is now planning to support `GPT-4 Turbo`. I hope this PR can be merged as soon as possible.

**Comment by danrasmuson** [comment]
Yes. Agreed. This PR supports a lot of us

**Comment by dqbd** [comment]
Hello! Sorry for the delay, released a new version of `js-tiktoken@1.0.7` and `tiktoken@1.0.11` which both add support for newer GPT-4-turbo and GPT-3.5-models.

Thank you @pkallos for the contribution!

**Comment by missuo** [comment]
> Hello! Sorry for the delay, released a new version of `js-tiktoken@1.0.7` and `tiktoken@1.0.11` which both add support for newer GPT-4-turbo and GPT-3.5-models.
> 
> 
> 
> Thank you @pkallos for the contribution!

Thanks!

**Comment by pkallos** [comment]
> Hello! Sorry for the delay, released a new version of js-tiktoken@1.0.7 and tiktoken@1.0.11 which both add support for newer GPT-4-turbo and GPT-3.5-models.
> 
> Thank you @pkallos for the contribution!

Thanks!

**Pull request closed without merging**
